### ISSUE TITLE
Incorrect extraneous index calculations

### ISSUE THREAD

**Issue by adsteel** [gregnavis/active_record_doctor#4]
Applicable readme section: https://github.com/gregnavis/active_record_doctor#removing-extraneous-indexes.

For the sake of this explanation, let's say we have a `rooms` table that has `rooms.room_number` and `rooms.floor_number`. We build a multi-column index with `floor_number` first, `room_number` second.

A multi-column index in SQL works by (essentially) concatenating the values of the two columns. Here's a simplified drawing of that:

```
floor_number_room_number_index
1;1
1;2
1;3
2;1
2;2
2;3
```

Indexes are fast in part because they group the values. In the example above, only the `floor_number` is grouped together. So this index will work for `floor_number`. But `room_number` is not grouped, and the database is smart enough to know that. It will not use this index for `room_number`, but will do a full table search instead.

The worst part of all this is that it is even more complicated than that. Check out [this article](http://www.sqlskills.com/blogs/kimberly/how-can-you-tell-if-an-index-is-really-a-duplicate/) for a more complete explanation. There's also a useful [SO question](http://stackoverflow.com/questions/179085/multiple-indexes-vs-multi-column-indexes) on the topic.

**Comment by gregnavis** [comment]
Thanks for reporting. I'd like to ask you for some clarification. Could you provide an example incorrect output and the expected result? Or is this the problem with the README only?

I'm looking at README right now and I misused notation that I adopted. The list in _Removing Extraneous Indexes_ reads:

* `column_1`
* `column_1`, `column_2`
* …
* `column_1`, `column_2`, …, `column_(n - 1)`

but it should be:

* `column_1`
* `column_1, column_2`
* …
* `column_1, column_2, …, column_(n - 1)`

My impression is that the problem is only in the README. Going back to your example, if the `rooms` table has a two-column index on `(floor_numer, room_number)` and a single-column index on `room_number` then the latter index will **not** be reported as extraneous.

**Comment by adsteel** [comment]
You are correct, this works correctly. Actually, I misread the readme, so I'm not even sure that's incorrect. Sorry for the false issue!
