### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by fatkodima** [gregnavis/active_record_doctor#59]
I have some improvements in mind, but need to verify this is aligned with the project goals, before implementing.

1. Currently, we can run one check at a time. Would be better to have some command (`bin/active_record_doctor`) to simply run *all* checks.
2. There is no way to configure the behavior. Would be good to have some config file (`.yml`) to be able to setup, for example, which checks to skip or which table/columns to ignore.
3. There is some code regarding loading/reloading - `minitest-fork_executor` gem, `test/model_factory.rb`, code in `test/setup.rb`. I can reimplement how things are tested and get rid of all of that.
4. Gem depends on `rails`, `railties`, `activerecord`, `activesupport`, but should really depend on `activerecord` only
5. Gem supports only postgresql. Would be great to support also mysql. For sqlite it seems useless.
6. There is no way to easily run a test suite against all the Gemfile's - needs to use `BUNDLE_GEMFILE=... bundle exec rake`. May be a good idea to add a dev dependency on `appraisals` gem to do this.
7. Make it easier to use on CI.
8. Some checks can cause a lot of unnecessary db queries while checking (for example, https://github.com/gregnavis/active_record_doctor/blob/a9ab257ade16e3caad7a7d8f66b1576b8a9599b7/lib/active_record_doctor/detectors/missing_foreign_keys.rb#L22-L23), so to use some caching/memoization
9. Be able to run it on non-rails applications

**Comment by gregnavis** [comment]
Thank you for your comment. Let me address the issues you raised one-by-one:

1. It's been on the agenda for some time and I pushed the first implementation to `master` today.
2. Also on the agenda -- happy to hear your input on this. I do have a design in mind but haven't had time to write it up yet.
3. I'll address them separate at the end.
4. Minor correction, the gem does **not** depend on `rails` for production. Seems these are remnants of the gem's past and can now be removed. Thanks for the suggestion!
5. See #54.
6. Currently, the gem files are simple that I wouldn't like to increase the complexity of the project by adding a separate dependency. I think a shell script might be enough here.
7. As of now, `master` has `active_record_doctor:all` which reports all problems and signals success/failure with exit status. What else do you think would be necessary?
8. Do you think those queries would affect the experience of using the tool given it's development- and/or CI-only? I'm hesitant to add caching as it's complexity that doesn't seem to solve a real problem here.
9. That's definitely on the roadmap!

Regarding 3, those were added to solve some specific problems. I'm happy to have a look at alternatives if you think there's a better way:

- `minitest-fork_executor` was built to remove test case interference caused by invalid class garbage collection. I wrote this up in [an article](https://www.gregnavis.com/articles/how-to-reduce-test-interference-in-minitest.html). It seems disabling it (by commenting out the last line in `setup.rb`) leads to some issues. This makes me think it's presence is still valid. Do you have any solutions in mind?
- `model_factory.rb` - we need a way to create and remove test models and tables. I used to use `temping` but not it's unmaintained and it turned out a small module is a good enough replacement. What alternative do you see here?

Thanks for your comments and suggestions. Some of the stuff is definitely on the roadmap.

**Comment by fatkodima** [comment]
With recent commits, only configuration is left, so I think that this can be closed.
